### ISSUE TITLE
biber

### ISSUE THREAD

**Issue by bennn** [bennn/luau-telemetry#1]
@asajeffrey I can't seem to reach your email:

1. The missing files are my problem, I'll check later today
2. I think `biber` is required by Programming
3. SI is desired by Programming. They'll ask for it at camera-ready.

**Comment by bennn** [comment]
Ah, okay. Biber / BibLaTeX is preferred but plain bibtex is okay.

Source: the pdf in Programming's tex template zipfile [example-programming.pdf](https://github.com/bennn/luau-telemetry/files/12581195/example-programming.pdf)

**Comment by asajeffrey** [comment]
We had an SMTP failure at work I think. Should be fixed now.
